### ISSUE TITLE
Destination path is created along with converted file

### ISSUE THREAD

**Issue by suhasKaginkar** [AmadeusITGroup/protractor-to-playwright#27]
When trying to convert  .js files using npx @amadeus-it-group/protractor-to-playwrite@latest --file='xxx\xx\file.js' --dst='tests\xxx\xxx'   We are getting converted file. js along with its original path created in the destination folder

**Comment by fbasso** [comment]
I think you should try to use the --src and --dst together. They represent folder paths relative to the current folder (from where you run your command). --file is the pattern to use in order to match specific files (by default, it's `**/*.{ts,js}`).

Then yes, the folder structure in the dst folder will be the same as the src one.

**Comment by suhasKaginkar** [comment]
Thanks
