### ISSUE TITLE
async keyword is missing in the test specs when converted

### ISSUE THREAD

**Issue by suhasKaginkar** [AmadeusITGroup/protractor-to-playwright#28]
When tried to convert protractor script to playwright for some specs async keyword is not getting generated.

**Comment by fbasso** [comment]
Hi @suhasKaginkar, thanks for reporting.

Can you share more context about the issue ? It's quite hard to fix an issue if we can't reproduce it.

**Comment by divdavem** [comment]
Hi @suhasKaginkar 
We have added a test in [#29](https://github.com/AmadeusITGroup/protractor-to-playwright/pull/29/files) to check that the async keyword is correctly added.
If you have found another case in which the async keyword is not added correctly, please send us the details so that we can fix the issue. Thank you!

**Comment by suhasKaginkar** [comment]
Thanks

**Comment by suhasKaginkar** [comment]
Hi @fbasso 
 We are using 'JavaScript' as a Scripting language, the issue is we are not able to resolve a promise due to following....

Pleas find below the screenshot
![Screenshot 2022-07-25 121000](https://user-images.githubusercontent.com/108995552/180714210-b184edd2-3aca-4593-b4cd-038035ace59f.png)

Actual: as you can see at line no.7 the async keyword is missing before 'function'

Expected: 'async' keyword should be present to return a promise

**Comment by divdavem** [comment]
@suhasKaginkar This issue should now be fixed in version 1.3.0 of protractor-to-playwright.
